language: java

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.cache
    - $HOME/.m2

script:
  - ./ci/build.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker push akvo/flow-api-backend;
    fi

env:
  global:
  - secure: Ygk8w+EIBfKgG0B4eQewt/nbAyzO2Y880RfC8QwQ8nBi395AsT/rD6P3WQLWCwvk1av/+X2SYSMC6uWt/6d0qdqRSdj7+9wtrsTQGhvgaAVf4JUQo5Jmtq7iYdTOFy67WTUnonbW4eIm4lVaSWTgvokTSWS4wX00OCwXMkT2n1Ps9JGXwY4U6QT0ofWPZuUamNj4vnb4xpKga9qth0XGc2HIR9Bx/AhsjY7lQx2WPu3qoenIMXoq/yCHfKouK1KoJumFhOCje1nxcflS3YWHUb9P61FHus04Fc9wDvJ4PQxfzpn0DvU31sZI8dtm6rdcCfXqFneftgaCc41xGLBARfY6HbAAIoxWNKd4ZAoLdrs021fcyjQqJkoDdEBERsnC60miiZGot1m8ANr9RA95qlAFcXa0u5fOZ+Vl4w2eQMUacmu2ppnBOOhQSpEO+phydhLx37ukmnCt1M2E53MtEVwvPcWsHDTQ3Kgf3GnQZpNv8p6btYWISVjq6TmYJZpkrceiXlppmGUkGk0x1fziG4Zz3OpZQ86XiRTEiqDB8bVR0TSwKv8ifRdmuEODKkx18vyN2q/wwbSTRpqhOISfob6KmxkeOl6vc3/DcNah5BCMK8Ch6gf6hHFmWjOSNBqL5+kXgoEyEOIqxOLTdFLOWVa+ZPISY6u46NhD1/qmAos=
  - secure: qNXQuYipMI4/1hkF7HKvS3UwlTrt6U15hzIzPT6UpWfq+HiMgEhIEbXihviYLGyvnQO6JmtmYEpRkuA4nUZFZCfiySxkVfMFVpiOHIy1o+RheqmXVkQ0Vckh4DWCLvXE1ZC/cTD3PaD6x5okJd1fuT2U4xP4Nipsyxgs0wLyvIFw2ScVVeWh1/qV0CROMM4e0qeHd7ahTs6XbiWQ+nKuQasKAoPGWokOSD38pWUdfUYvydCQesEdD2UkXtVCHOgXErYQYZk6YMnX/+fCdJGEkvNjk4pH+0uYu9XHsODK8v81AYapA2ua+029d7m6ACOqJHJVoAGLZubGcLeidWLDePbRaqA8SmyfFq/tl4+nol4toYmJNKwKY0CjqX+4yTbZBUUebC5T856BLYWeOZB6GISzvnDFMNUPw6aQiWHL9V+1ytUu0O9LOb8YW5O0UIDWmv/E3/5JsXUbtuLnqzIGZj7yN29wwTrwOjJOmvMDG7oEo3jv5JxutChkurEitPWUXn0DLXbaNxmRFb5Fu42eBEnbT0KMJdL9S7ipHWrybJBhU0LvvdXMlm2TzqqtRpIcH2tCAcLHNb8mRJFSGVnjUquHqsU7aiT3S6nKPs1wEPmxTpqJaG82546uu0UHOWZtK9Hf4bAFschLli74iLmllnuIPp9Y4g60wD4C+YBaq2M=
