language: java

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.cache
    - $HOME/.m2

script:
  - ./ci/build.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push akvo/flow-api-backend;
    fi

env:
  global:
  - secure: dfKABVXV+5dbdTgs2AjevfnSzMPSgVuUr9W6ko6GXGXLLq18KFA/x3LQxt5LIxvnyGg0HmY5X3NYPLpEXipBR9oIv7cwu9exklMLoHukheJDKtVz5jKFXCvUQO1/y8n1zVmXZqVv8DT0j18h8sN4DPz+2V1c9ib2iOZiBTqquq3sRWljR1d+3zonIhETzGgbwFMC6dOTiDbSxRPkTYs0PvIV7hs6pWHpY5hjSWB9haTYlhkBtXBOn10sQlGvNBYOX2ZFlWxojzz2iK4QpnC+3zI8JVhv8luNL5N2opyLZx5WDB2qUHeyNkKZocs7w1P+vbzl1Ktso3ooBykXdmNkjIsjqMv0EFzwtRcPHFmOjitjjPogZOi9knsbUO9f//sag0tOiw2WIgyXr1boUKVFY8PKhyFzra8tCVNzhHfU6Q5ZXz9bWfQxPGIiASoyh2ZzCXApnvAmfMJH+QmqGNCcGxxgUCSKk4cs3kKIP22LkOWRIMPpLctaKB1uqnC2qHzO02mkxvzbozZPycc9lU99aPk49I8gqPZU6E6zfSs7HitRu9wjCVF++wISwQWXL9okbn45IJGuQzHnCHVQgU4AAOUAjSng3cTJRxOZLmRgl1ykKBJfekeBiZ4I15bw4RdZhqzblb3rqVnel07EvSYRdirx02+FUId+0Ax3p74FjVc=
  - secure: a/8OeT83TD5anD3reSJJr54pcT5Y1zXz1AIkr8xqp6H6cJNjvli0OXpqskNq92HXUEhVFlzruyDCc05zilGST3CANInc1wBATgXuzbwSxO5MpibkRm6rS5TTJBUUj6MIzdOKd262GZIbtVSOYFLpdaB3wDU1Y26skmbnlREOiqoS9+7lONwYAhqdXfJIpFI8aJEiQmWgoMM5eSxim5VnpopHhA8P0nTEy0kzIxzajZl+psagjt1zp4bt0hZMpv4V6WncrSbT0mXSNtkYyLjHQM7haEe8f9vOH2i1RaFDeoAgkQJDK4+T13IuQ0Lc6TYcadITm8z9W+JAlEPevsN7OQhDK/i5OZU3pdT7qLvmaKZw6ojxEpu2qwslqA4k3ZRT3OhvHOEns+/lXb+bnW9WRE1GLGbUn4wMBUWPzFo0Y5DQTjb4U13tWh0Vnw5RmpIrkhoYWa3ya2yPVrcvUzdG/7NsvQCd1gyViP7JMSIBMVQFo3S8M3Y3E7196huKYWI7BocospQHW/fv5KdYKXNJVxdIjfJd1PtbzVhw05qQ2iVbl4GVKL77qykcHynw2pDyVT0wr2Ewn+iD4bWOu232dn1oFiDw2t5uu7vfUwTrj3LMi2KRpbeIan9Q+ZV7uWUYa1kUEqRqaM51Ok6pzpG0JrBwCjhGd3GR2vvOa3+P37o=
