version: "3"
services:
 mainnetwork:
    image: alpine
    command: tail -f /dev/null
 gae-dev-server:
   build: gae-dev-server
   network_mode: service:mainnetwork
   volumes:
     - ~/.m2:/home/akvo/.m2
     - ~/.m2:/root/.m2
     - ./gae-dev-server:/app
 flow-api:
   network_mode: service:mainnetwork
   environment:
     TAOENSSO_TIMBRE_CONFIG_EDN: "{ :min-level :info }"
     TIMBRE_LEVEL: ":info"
     TAOENSSO_TIMBRE_MIN_LEVEL_EDN: ":warn"
   volumes:
     - ~/.m2:/home/akvo/.m2
     - pg-data:/pg-certs:ro
 wiremock-proxy:
   image: rodolpheche/wiremock:2.16.0-alpine
 unilog:
   image: akvo/akvo-postgres-11:20190222.b31bfb0
   network_mode: service:mainnetwork
   environment:
     - POSTGRES_PASSWORD=akvo
   volumes:
     - ./unilog/initdb:/docker-entrypoint-initdb.d:ro
     - pg-data:/var/lib/postgresql/data
volumes:
   pg-data:
