version: "3"
services:
 mainnetwork:
    ports:
      - "47480:47480"
      - "3000:3000"
      - "8889:8888"
 flow-api:
   build:
     context: .
     dockerfile: api/Dockerfile-dev
   volumes:
      - ./api:/app
      - ~/.m2:/root/.m2
      - ~/.m2:/home/akvo/.m2
      - ~/.lein:/root/.lein
      - ~/.lein:/home/akvo/.lein
 wiremock-proxy:
   ports:
     - 8081:8080
