version: "3"
services:
 mainnetwork:
 flow-api:
   build:
     context: .
     dockerfile: api/Dockerfile-dev
   volumes:
      - ./api:/app
      - ~/.m2:/root/.m2
      - ~/.lein:/root/.lein
 tests:
   build:
     context: .
     dockerfile: api/Dockerfile-dev
   network_mode: service:mainnetwork
   volumes:
      - ./api:/app
      - ~/.m2:/root/.m2
      - ~/.m2:/home/akvo/.m2
   depends_on:
      - flow-api
      - unilog
   command: "true"
