apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: flow-api
spec:
  tls:
  - hosts:
    - "api.akvotest.org"
    secretName: tls
  rules:
    - host: "api.akvotest.org"
      http:
        paths:
        - backend:
            serviceName: flow-api
            servicePort: 80
