version: "3"

services:
  testnetwork:
    image: alpine:3.10
    entrypoint: "/usr/local/src/entrypoint.sh"
    command: ["tail", "-f", "/dev/null"]
    ports:
      - 8082:8082
    volumes:
      - ./:/usr/local/src:ro
    environment:
      - AUTH0_USER
      - AUTH0_PASSWORD
  nginx-auth0:
    image: akvo/flow-api-auth0-proxy:latest
    network_mode: service:testnetwork
    environment:
      - FLOW_API_BACKEND_URL=http://localhost:3000
      - OIDC_DISCOVERY_URL=https://akvotest.eu.auth0.com/.well-known/openid-configuration
      - OIDC_EXPECTED_ISSUER=https://akvotest.eu.auth0.com/
  upstream:
    image: akvo/flow-api-auth0-proxy:latest
    network_mode: service:testnetwork
    entrypoint: ["/usr/local/openresty/bin/openresty", "-c", "/usr/local/src/nginx-test.conf", "-g", "daemon off;"]
    volumes:
      - ./:/usr/local/src:ro
