---
apiVersion: "config.istio.io/v1alpha2"
kind: denier
metadata:
  name: flow-api-handler
  namespace: default
spec:
  status:
    code: 16
    message: You are not authorized to access the service
---
apiVersion: "config.istio.io/v1alpha2"
kind: checknothing
metadata:
  name: flow-api-denyrequest
  namespace: default
spec:
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: flow-api-deny
  namespace: default
spec:
  match: destination.labels["run"] == "dantest-flow-api" && (request.auth.principal|"unauthorized") == "unauthorized"
  actions:
  - handler: flow-api-handler.denier.default
    instances: [flow-api-denyrequest.checknothing.default]
---
apiVersion: "config.istio.io/v1alpha2"
kind: denier
metadata:
  name: flow-api-accept-handler
  namespace: default
spec:
  status:
    code: 3
    message: Invalid Accept request header
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: flow-api-accept-deny
  namespace: default
spec:
  match: destination.labels["run"] == "dantest-flow-api" && (request.headers["accept"]|"nothing") != "application/vnd.akvo.flow.v2+json"
  actions:
  - handler: flow-api-accept-handler.denier.default
    instances: [flow-api-denyrequest.checknothing.default]
---
apiVersion: "config.istio.io/v1alpha2"
kind: denier
metadata:
  name: flow-api-user-agent-handler
  namespace: default
spec:
  status:
    code: 3
    message: Invalid user agent
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: flow-api-user-agent-deny
  namespace: default
spec:
  match: destination.labels["run"] == "dantest-flow-api" && (request.headers["user-agent"]|"nothing") == "nothing"
  actions:
  - handler: flow-api-user-agent-handler.denier.default
    instances: [flow-api-denyrequest.checknothing.default]
---
