apiVersion: v1
kind: Service
metadata:
  name: dantest-flow-api
  annotations:
    auth.istio.io/80: MUTUAL_TLS
    auth.istio.io/8080: MUTUAL_TLS
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    run: dantest-flow-api
