apiVersion: v1
kind: Service
metadata:
  name: flow-api
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    run: flow-api
---
apiVersion: v1
kind: Service
metadata:
  name: flow-api-auth0
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    run: flow-api
