apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: flow-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: flow-api
    spec:
      containers:
      - name: flow-api-backend
        image: akvo/flow-api-backend
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
        - name: secrets
          mountPath: /secrets
        env:
        - name: SECRETS_MOUNT_PATH
          value: "/secrets"
        - name: HTTP_PORT
          value: "3000"
        - name: API_ROOT
          value: "https://api.akvo.org/flow"
      volumes:
      - name: secrets
        secret:
          secretName: flow-api-secrets
