FROM clojure:lein-2.8.1

RUN set -ex; \
    apt-get update && apt-get install -y --no-install-recommends \
    gosu && \
    rm -rf /var/lib/apt/lists/* && \
    useradd -d /home/akvo -m -s /bin/bash akvo

WORKDIR /app

CMD [ "dev/run-as-user.sh", "dev/start-dev-env.sh" ]
